apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: awsome-architechs
        image: public.ecr.aws/m6p2m6g2/backend:22
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app.kubernetes.io/part-of: backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    prometheus.io/port: "metrics-port"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: metrics-port
  type: LoadBalancer
